flowchart TD
    A[Inici - Benvinguda] -->|Accedir| B[Login]
    A -->|Registrar-se| C[Registre]
    B -->|Credencials correctes| D[Home - Pantalla principal]
    C -->|Registre completat| D
    D -->|Explorar pegats| E[Llista de pegats]
    E -->|Seleccionar pegat| G[Hores actives del pegat]
    D -->|Accedir al perfil| J[Perfil de l'usuari]
    J -->|Modificar dades| K[Editar perfil]
    J -->|Configuració| L[Configuració]
    L -->|Tancar sessió| A
