flowchart TD
    A[Inici - Benvinguda] -->|Accedir| B[Login]
    A -->|Registrar-se| C[Registre]
    B -->|Credencials correctes| D[Home - Pantalla Principal]
    C -->|Registre Completat| D
    D -->|Explorar Tapes| E[Llista de pegats]
    D -->|Veure Mapa| F[Mapa de Tapes]
    E -->|Seleccionar pegat| G[Hores actives del pegat]
    F -->|Seleccionar pegat| G
    G -->|Veure perfil del usuari| I[Perfil del usuari]
    D -->|Accedir al Perfil| J[Perfil de l'usuari]
    J -->|Modificar Dades| K[Editar Perfil]
    J -->|Configuració| L[Configuració]
    L -->|Tancar Sessió| A
