classDiagram
    class User {
        +int id
        +varchar username(20)
        +varchar password(20)
        +varchar email(50)
    }

    class Rol {
        +int id
        +varchar type_rol(20)
    }

    class RelationUserChild {
        +int user_id
        +int child_id
        +int rol_id
    }

    class Child {
        +int id
        +varchar child_name(50)
        +int sleep_average
        +int treatment_id
        +int time
    }

    class Treatment {
        +int id
        +varchar name(11)
    }

    class Status {
        +int id
        +varchar name(40)
    }

    class Tap {
        +int id
        +int child_id
        +int status_id
        +int user_id
        +datetime init
        +datetime end
    }